<?php

declare(strict_types=1);

namespace App\Relating\Factory;

use App\Relating\Entity\RelationActivity;
use App\Relating\Entity\RelationLead;
use App\Relating\Entity\RelationOpportunity;
use App\Relating\Entity\RelationPipeline;
use App\Relating\Entity\RelationPipelineStage;
use App\Relating\Entity\Relationship;
use App\Relating\Entity\RelationTimelineRecord;
use App\Relating\Enum\RelationActivityDirection;
use App\Relating\Enum\RelationActivityType;
use App\Relating\Enum\RelationForecastCategory;
use App\Relating\Enum\RelationLeadTemperature;
use App\Relating\Enum\RelationshipKind;
use App\Relating\Enum\RelationTimelineRecordKind;

final class RelationRelatingDemoEntityFactory
{
    /**
     * @return array{relationship: Relationship, timeline: RelationTimelineRecord, activity: RelationActivity}
     */
    public function relationshipStart(): array
    {
        $relationship = new Relationship('relationship_demo_001', 'vendor_demo_001', RelationshipKind::Prospect);
        $relationship->assignTenant('tenant_demo');
        $relationship->assignOwner('user_demo_owner');
        $relationship->markTouch();

        $timeline = new RelationTimelineRecord(
            'timeline_demo_relationship_started',
            'relationship',
            $relationship->id(),
            RelationTimelineRecordKind::RelationshipStarted,
            ['business_operation' => 'start_relationship'],
        );
        $timeline->attachRelationship($relationship->id());

        $activity = new RelationActivity(
            'activity_demo_follow_up',
            RelationActivityType::Task,
            'relationship',
            $relationship->id(),
            RelationActivityDirection::Internal,
        );
        $activity->attachRelationship($relationship->id());
        $activity->describe('Follow up on relationship start', 'Demo follow-up task generated by business lifecycle seed.');

        return [
            'relationship' => $relationship,
            'timeline' => $timeline,
            'activity' => $activity,
        ];
    }

    /**
     * @return array{lead: RelationLead, timeline: RelationTimelineRecord}
     */
    public function qualifiedLead(): array
    {
        $lead = new RelationLead('lead_demo_001', [
            'source' => 'web_form',
            'business_operation' => 'capture_lead',
        ]);
        $lead->assignTenant('tenant_demo');
        $lead->identify('Demo Buyer', 'Demo Company', 'demo@example.test', '+15550000000');
        $lead->setSourceReference('source_demo_web_form');
        $lead->qualify(82, RelationLeadTemperature::Hot);

        $timeline = new RelationTimelineRecord(
            'timeline_demo_lead_qualified',
            'lead',
            $lead->id(),
            RelationTimelineRecordKind::LeadQualified,
            ['score' => $lead->score(), 'business_operation' => 'qualify_lead'],
        );

        return [
            'lead' => $lead,
            'timeline' => $timeline,
        ];
    }

    /**
     * @return array{pipeline: RelationPipeline, discoveryStage: RelationPipelineStage, proposalStage: RelationPipelineStage, opportunity: RelationOpportunity, timeline: RelationTimelineRecord}
     */
    public function opportunityFlow(): array
    {
        $pipeline = new RelationPipeline('pipeline_demo_sales', 'sales_pipeline', 'Demo Sales RelationPipeline');
        $pipeline->assignTenant('tenant_demo');
        $pipeline->markDefault(true);

        $discoveryStage = new RelationPipelineStage(
            'stage_demo_discovery',
            $pipeline->id(),
            'discovery',
            'Discovery',
            10,
            25,
            RelationForecastCategory::Pipeline,
        );

        $proposalStage = new RelationPipelineStage(
            'stage_demo_proposal',
            $pipeline->id(),
            'proposal',
            'Proposal',
            20,
            55,
            RelationForecastCategory::BestCase,
        );

        $opportunity = new RelationOpportunity(
            'opportunity_demo_001',
            'relationship_demo_001',
            $pipeline->id(),
            $discoveryStage->id(),
            'Demo commercial opportunity',
        );
        $opportunity->assignTenant('tenant_demo');
        $opportunity->setAmount('USD', 250000);
        $opportunity->setPrimaryProductReference('product_demo_001');
        $opportunity->moveToStage($proposalStage->id(), 55, RelationForecastCategory::BestCase);

        $timeline = new RelationTimelineRecord(
            'timeline_demo_opportunity_stage_changed',
            'opportunity',
            $opportunity->id(),
            RelationTimelineRecordKind::OpportunityStageChanged,
            [
                'from_stage' => $discoveryStage->id(),
                'to_stage' => $proposalStage->id(),
                'probability' => 55,
                'business_operation' => 'change_stage',
            ],
        );
        $timeline->attachRelationship('relationship_demo_001');

        return [
            'pipeline' => $pipeline,
            'discoveryStage' => $discoveryStage,
            'proposalStage' => $proposalStage,
            'opportunity' => $opportunity,
            'timeline' => $timeline,
        ];
    }
}
