<?php

declare(strict_types=1);

namespace App\Factory;

use App\Entity\Activity;
use App\Entity\Lead;
use App\Entity\Opportunity;
use App\Entity\Pipeline;
use App\Entity\PipelineStage;
use App\Entity\Relationship;
use App\Entity\TimelineRecord;
use App\Enum\ActivityDirection;
use App\Enum\ActivityType;
use App\Enum\ForecastCategory;
use App\Enum\LeadTemperature;
use App\Enum\RelationshipKind;
use App\Enum\TimelineRecordKind;

final class RelatingDemoEntityFactory
{
    /**
     * @return array{relationship: Relationship, timeline: TimelineRecord, activity: Activity}
     */
    public function relationshipStart(): array
    {
        $relationship = new Relationship('relationship_demo_001', 'vendor_demo_001', RelationshipKind::Prospect);
        $relationship->assignTenant('tenant_demo');
        $relationship->assignOwner('user_demo_owner');
        $relationship->markTouch();

        $timeline = new TimelineRecord(
            'timeline_demo_relationship_started',
            'relationship',
            $relationship->id(),
            TimelineRecordKind::RelationshipStarted,
            ['business_operation' => 'start_relationship'],
        );
        $timeline->attachRelationship($relationship->id());

        $activity = new Activity(
            'activity_demo_follow_up',
            ActivityType::Task,
            'relationship',
            $relationship->id(),
            ActivityDirection::Internal,
        );
        $activity->attachRelationship($relationship->id());
        $activity->describe('Follow up on relationship start', 'Demo follow-up task generated by business lifecycle seed.');

        return [
            'relationship' => $relationship,
            'timeline' => $timeline,
            'activity' => $activity,
        ];
    }

    /**
     * @return array{lead: Lead, timeline: TimelineRecord}
     */
    public function qualifiedLead(): array
    {
        $lead = new Lead('lead_demo_001', [
            'source' => 'web_form',
            'business_operation' => 'capture_lead',
        ]);
        $lead->assignTenant('tenant_demo');
        $lead->identify('Demo Buyer', 'Demo Company', 'demo@example.test', '+15550000000');
        $lead->setSourceReference('source_demo_web_form');
        $lead->qualify(82, LeadTemperature::Hot);

        $timeline = new TimelineRecord(
            'timeline_demo_lead_qualified',
            'lead',
            $lead->id(),
            TimelineRecordKind::LeadQualified,
            ['score' => $lead->score(), 'business_operation' => 'qualify_lead'],
        );

        return [
            'lead' => $lead,
            'timeline' => $timeline,
        ];
    }

    /**
     * @return array{pipeline: Pipeline, discoveryStage: PipelineStage, proposalStage: PipelineStage, opportunity: Opportunity, timeline: TimelineRecord}
     */
    public function opportunityFlow(): array
    {
        $pipeline = new Pipeline('pipeline_demo_sales', 'sales_pipeline', 'Demo Sales Pipeline');
        $pipeline->assignTenant('tenant_demo');
        $pipeline->markDefault(true);

        $discoveryStage = new PipelineStage(
            'stage_demo_discovery',
            $pipeline->id(),
            'discovery',
            'Discovery',
            10,
            25,
            ForecastCategory::Pipeline,
        );

        $proposalStage = new PipelineStage(
            'stage_demo_proposal',
            $pipeline->id(),
            'proposal',
            'Proposal',
            20,
            55,
            ForecastCategory::BestCase,
        );

        $opportunity = new Opportunity(
            'opportunity_demo_001',
            'relationship_demo_001',
            $pipeline->id(),
            $discoveryStage->id(),
            'Demo commercial opportunity',
        );
        $opportunity->assignTenant('tenant_demo');
        $opportunity->setAmount('USD', 250000);
        $opportunity->setPrimaryProductReference('product_demo_001');
        $opportunity->moveToStage($proposalStage->id(), 55, ForecastCategory::BestCase);

        $timeline = new TimelineRecord(
            'timeline_demo_opportunity_stage_changed',
            'opportunity',
            $opportunity->id(),
            TimelineRecordKind::OpportunityStageChanged,
            [
                'from_stage' => $discoveryStage->id(),
                'to_stage' => $proposalStage->id(),
                'probability' => 55,
                'business_operation' => 'change_stage',
            ],
        );
        $timeline->attachRelationship('relationship_demo_001');

        return [
            'pipeline' => $pipeline,
            'discoveryStage' => $discoveryStage,
            'proposalStage' => $proposalStage,
            'opportunity' => $opportunity,
            'timeline' => $timeline,
        ];
    }
}
